Sage-Bionetworks/projectLive_NF

- projectLive/R/mod_study_lead.R
- projectLive/R/mod_summary_snapshot.R
Making the study_upload_timeline box and plot bigger for better readability
> Changing box and plot size

- projectLive/R/app_config.R
- projectLive/R/app_server.R
- projectLive/R/app_ui.R
- projectLive/R/mod_about_page.R
- projectLive/R/synapse_functions.R
- projectLive/R/zzz.R
- projectLive/inst/app/www/readCookie.js
Starting a new PR to incorporate changes in #47 and #49 to new-master branch. The default branch has been changed from master to new-master due to conflict resolution issues.
> adding synapse token to new-master

- R/data_manipulation_functions.R
- R/mod_about_page.R
- R/mod_study_summary.R
- R/plot_functions.R
- inst/data_config.json
- tests/testthat/test-data_manipulation_functions.R
- tests/testthat/test-plot_functions.R
[42](https://github.com/jaybee84/projectLive/issues/42)
> Add issue 42 plot

- .gitignore
- R/mod_about_page.R
1. adding \man to gitignore, 2. adding back to data portal button in about page (closes #53 )
> back to portal button

- R/app_server.R
- R/app_ui.R
- R/mod_about_page.R
- renv.lock
Adding a loading screen. 
can see it in action here  https://shiny.synapse.org/users/rallaway/projectLive/
> add waiter

- R/mod_about_page.R
hide_waiter() seems to be deprecated.. so updating it to waiter_hide()
> change hide_waiter() to waiter_hide()

- renv.lock
update version of lubridate pkg to get rid of unwanted warning msgs
> update renv.lock 

- inst/study_summary_module.json
- inst/summary_snapshot_module.json
- renv.lock
> Update projectlive modules

- data-raw/files.R
- data-raw/studies.R
rename initiative column to consortium for v1.0
> Rename initiative col to consortium

- inst/publication_status_module.json
- inst/summary_snapshot_module.json
1. remove space in jsons, 
2. change facet of initiative activity plot back to year
> add minor edits

- inst/summary_snapshot_module.json
> adding pendingAnnotation label for na

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- R/app_server.R
- data-raw/files.R
- data-raw/incoming_data.R
- data-raw/studies.R
- data-raw/tools.R
- inst/data_config.json
Reverts Sage-Bionetworks/projectLive#130
> Revert "Update synapse auth"

- create_rds_files/create_rds_files.R
- inst/publication_status_module.json
- inst/study_summary_module.json
- renv.lock
> fix issue with publication plot scales

- README.md
Reverts Sage-Bionetworks/projectLive_NF#161
> Revert "Release on Shinyapps.io - 1"

- inst/study_summary_module.json
> update json to include files with missing annotations

- inst/new_submissions_module.json
- oauth_config.yaml
- renv.lock
> updated projectlive.module, and json file

- R/app_server.R
- inst/study_summary_module.json
- renv.lock
> update procjetlive.modules, use dev data

- R/app_server.R
- inst/study_summary_module.json
- renv.lock
> Issue 177 missing milestones

- R/global.R
> do chmod on virtualenv before using

- oauth_config.yaml
> reomove ignored file
